kind: Deployment
apiVersion: apps/v1
metadata:
  name: linreg-api-deployment
  labels:
    app: linreg-api
spec:
  selector:
    matchLabels:
      app: linreg-api
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: linreg-api
    spec:
      containers:
        - name: linreg-api
          image: purefr0st/linreg-api:0.0.1
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: 1
