apiVersion: v1
kind: Service
metadata:
  name: linreg-api-service
spec:
  type: NodePort
  selector:
    app: linreg-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 8000