# Change if you want to run this locally
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.1
  - fastapi=0.73.0
  - diskcache=5.4.0
  - scipy=1.7.3
  - gunicorn==20.1.0
  - uvicorn=0.17.3
